### ISSUE TITLE
Unable to run the sample code

### ISSUE THREAD

**Issue by jkalwar** [aspose-words-cloud/aspose-words-cloud-node#1]
Using the latest version of SDK : 19.10.0 
Node : 12.3.1

Running the sample code as given in the home page with the relevant parameters gives the below error 
```js
const { WordsApi, PostDocumentSaveAsRequest, SaveOptionsData } = require("asposewordscloud");

const AppSid = 'XXX'
const AppKey = 'XXX'

wordsApi = new WordsApi(AppSid, AppKey);

var request = new PostDocumentSaveAsRequest({
    name: "fileStoredInCloud.doc",
    saveOptionsData: new SaveOptionsData(
        {
            saveFormat: "pdf",
            fileName: "destination.pdf"
        })
});

wordsApi.postDocumentSaveAs(request)
    .then((result) => {
        // Deal with a result
        console.log(result.response.statusCode);
        console.log(result.body);
    })
    .catch(function(err) {
        // Deal with an error
        console.log(err.reponse.statusCode);
        console.log(err.body);
    });

```
Error:

var request = new PostDocumentSaveAsRequest({
              ^

TypeError: PostDocumentSaveAsRequest is not a constructor
    at Object.<anonymous> (/Users/jayakrishnaalwar/Documents/dpworld/_test_/pdfconverter.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11

**Comment by dmitry-finozhenok** [comment]
Thank you for your request.
The current version of the SDK uses SaveAsRequest instead of PostDocumentSaveAsRequest, and the method name is saveAs instead of postDocumentSaveAs.
The README.md is updated to reflect current naming.
